version: "3.7"

services:
  api:
    build:
      context: .
    environment:
      DB_NAME: parco
      DB_USER: parco
      DB_PASSWORD: parco
      DB_HOST: db
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - "./:/src/api"
      - "/src/api/node_modules"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: parco
      POSTGRES_USER: parco
      POSTGRES_PASSWORD: parco
    ports:
      - "5432:5632"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
volumes:
  postgres-data:
